name: Multi-Environment Deployment
 
on:
  push:
    branches:
      - dev
      - qa
 
jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: Dev
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
 
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment"
 
 
  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    environment: QA
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
 
      - name: Deploy to QA
        run: echo "Deploying to QA environment"
